### PR TITLE
Update Livid and Mimic msg to send in party chat

### PR DESCRIPTION
**Pull request by WhatYouThing**

### CODE REVIEW

**Comment by Fluboxer** [comment]
That should have a settings entry to choice if you want to use party chat for that

**Comment by viciscat** [comment]
agreed with Fluboxer

**Comment by WhatYouThing** [comment]
Score messages are always sent to the party chat, so I thought it would only make sense for these to also send to the party chat. Is there a specific reason for them sending to the all chat?

**Comment by Fluboxer** [comment]
> What happens with `/pc` when you're not in a party?

it will do this, even if you are not in party

изображение

**Comment by kevinthegreat1** [comment]
Is there consensus on this pr?

**Comment by Fluboxer** [comment]
my answer is no. I mean, it takes like a minute to code it into toggle-able setting

**Comment by Fluboxer** [comment]
while working on messages for my pr I noticed that... all score messages are trying to be sent in party chat?
изображение

I still consider this to be cancerous practice - there is no reason why you should hardcode that instead of either giving player a choice or just not doing so (/chat party exists)

**Pull request closed without merging**
