### PR TITLE
Update slayer icons

### PR DESCRIPTION
**Pull request by IllagerCaptain**
This PR changes all slayer icons in the profile viewer to the JAPPA textures, with exception of Revenant Horror, which uses Hypixel's custom texture. For vampire see #969.

### CODE REVIEW

**Comment by IllagerCaptain** [comment]
> I don't think it should be angry wolf. I'm also not entirely convinced using the playerhead instead of the zombie texture 🤔

Angry wolf is used in-game.

**Review by AzureAaron — APPROVED** [review]

**Comment by IllagerCaptain** [comment]
> It spends most as its time as a happy wolf in game. It's also known as zombie slayer so I think it should go with the zombie head (I also think the rev head without the 3d 'hat' elements makes it look rather silly) 

It does have the hat layer, it's just overlayed on top with the same scale as the main head, similar to skins in the tablist. I'm pretty sure the angry wolf texture not being used is a bug with newer versions on Hypixel, from all the sources I looked at it uses angry wolf in 1.8, which is likely the intended behavior.

**Comment by IllagerCaptain** [comment]
> > > It spends most as its time as a happy wolf in game. It's also known as zombie slayer so I think it should go with the zombie head (I also think the rev head without the 3d 'hat' elements makes it look rather silly) 
> > 
> > 
> > It does have the hat layer, it's just overlayed on top with the same scale as the main head, similar to skins in the vanilla tablist. I'm pretty sure the angry wolf texture not being used is a bug with newer versions on Hypixel, from all the sources I looked at it uses angry wolf in 1.8, which is likely the intended behavior.
> 
> I think it should stick with what we see rather than guessing intended behaviour. Angry wolf also looks very out of place on the menu.

Should it also be changed to use the ashen wolf skin, which is implemented on alpha?

**Comment by IllagerCaptain** [comment]
> > > > > It spends most as its time as a happy wolf in game. It's also known as zombie slayer so I think it should go with the zombie head (I also think the rev head without the 3d 'hat' elements makes it look rather silly) 
> > > > 
> > > > 
> > > > It does have the hat layer, it's just overlayed on top with the same scale as the main head, similar to skins in the vanilla tablist. I'm pretty sure the angry wolf texture not being used is a bug with newer versions on Hypixel, from all the sources I looked at it uses angry wolf in 1.8, which is likely the intended behavior.
> > > 
> > > 
> > > I think it should stick with what we see rather than guessing intended behaviour. Angry wolf also looks very out of place on the menu.
> > 
> > 
> > Should it also be changed to use the ashen wolf skin, which is implemented on alpha? 
> 
> If that's what they roll with for the mins too then ya, otherwise I think base wolf is fine

They did it for every wolf.

**Comment by IllagerCaptain** [comment]
> > > > > > > It spends most as its time as a happy wolf in game. It's also known as zombie slayer so I think it should go with the zombie head (I also think the rev head without the 3d 'hat' elements makes it look rather silly) 
> > > > > > 
> > > > > > 
> > > > > > It does have the hat layer, it's just overlayed on top with the same scale as the main head, similar to skins in the vanilla tablist. I'm pretty sure the angry wolf texture not being used is a bug with newer versions on Hypixel, from all the sources I looked at it uses angry wolf in 1.8, which is likely the intended behavior.
> > > > > 
> > > > > 
> > > > > I think it should stick with what we see rather than guessing intended behaviour. Angry wolf also looks very out of place on the menu.
> > > > 
> > > > 
> > > > Should it also be changed to use the ashen wolf skin, which is implemented on alpha? 
> > > 
> > > 
> > > If that's what they roll with for the mins too then ya, otherwise I think base wolf is fine
> > 
> > 
> > They did it for every wolf.
> 
> then i think thats sweet, as long as it doesnt look very dumb as a 2d head lol

They reverted it on this alpha.

**Comment by AzureAaron** [comment]
After some deciding we figure it would be best for the wolf icon to be the normal (non-hostile one), so once thats changed this can be merged.

**Review by AzureAaron — APPROVED** [review]

**Pull request merged**
