### PR TITLE
Use official hypixel wiki for WikiLookup

### PR DESCRIPTION
**Pull request by TacoMonkey11**

### CODE REVIEW

**Comment by Julienraptor01** [comment]
We'll have the option to choose which wiki we want to use ?
Cause if not, it would be nice to add it

**Comment by TacoMonkey11** [comment]
I guess that could be an option, I just don't see the point. The hypixel wiki seems to be better in almost every way

**Comment by Julienraptor01** [comment]
> I guess that could be an option, I just don't see the point. The hypixel wiki seems to be better in almost every way

The thing is that i'm more used with the old wiki and i know where things are while i need to search more than in the old wiki
Maybe the better solution would have to have 2 keybinds one for the old and one for the new because sometimes there might be one that is wrong and the other that is right so being able to check 2 sources is better

**Comment by TacoMonkey11** [comment]
A config option would  probably be better than another keybind

**Comment by Julienraptor01** [comment]
> A config option would  probably be better than another keybind

Yes but what if you want to quick look up both wikis because one seems wrong ?
You either need to type in your browser or to change config then look up then change config back

**Pull request merged**
