### PR TITLE
add new built-in texture pack for recolored textures in dungeons

### PR DESCRIPTION
**Pull request by btwonion**
hi,
i added a built-in texture pack which atm only contains a recolored tripwire(-hook):
image

i named the pack "recolored_dungeon_items" because i think there will come more textures in the future. (maybe)

### CODE REVIEW

**Comment by btwonion** [comment]
i thought it might be easier for the users to use a resourcepack, so they can decide whether to use it or not

**Comment by kevinthegreat1** [comment]
Yes, I mean datagen the resource pack. See https://fabricmc.net/wiki/tutorial:datagen_setup and `FabricDataGenerator.createBuiltinResourcePack`.

**Comment by btwonion** [comment]
oh okay. i will take a look at it

**Comment by kevinthegreat1** [comment]
I can help with this if you have any problems, or I can just do it.

**Comment by btwonion** [comment]
i currently do not have the time to do it. especially because im totally new to this. if you want to you can do it, but we can change this pr to a draft and i will do it later.

**Comment by btwonion** [comment]
i was able to recreate the blockstate configuration and the model.
the problem is, that i cannot find a proper way to datagen the element section of the model.

i furthermore removed the powered, attached and the tripwire hook configurations as in the dungeons there simply are no tripwire hooks and i dont think anybody would care about different textures for them in the use case here.

i left the old model and blockstate in the resources as a reference

**Comment by kevinthegreat1** [comment]
Thanks, I will take a look soon.

**Comment by btwonion** [comment]
waiiiiitt. haven't i pushed it?

**Comment by btwonion** [comment]
i had the whole thing recoded to datagen, but i forgot to push... and reset my system cause of a new component to my pc.

**Comment by kevinthegreat1** [comment]
Yes you did push it. I overrode those commits and reverted it since I couldn’t figure out datagen either. I have a copy of your commits and if you want those I can push them somewhere for you.

**Comment by kevinthegreat1** [comment]
Thanks for contributing!

**Pull request merged**
