### PR TITLE
make all formatting use static instances of numberformat using US locale

### PR DESCRIPTION
**Pull request by Julienraptor01**
Already tested :
- [x] Calculator command
- [x] Sign calculator
- [x] Chocolate factory solver
- [ ] End HUD widget
- [x] Visitor Helper

(once someone tell me they have validated that it still work with a screenshot i'll tick the box)

the changes are actually smth like 10 lines or so, but because auto-format on save...

### CODE REVIEW

**Comment by Julienraptor01** [comment]
i cannot test End HUD widget because killing zealots with a sword is just too slow
but it should very likely work

**Comment by kevinthegreat1** [comment]
The formatting is causing merge conflicts. The easiest way is to turn off auto format.

**Comment by Julienraptor01** [comment]
i just rebased and then used the version from head then saved
didn't need any complicated merge conflict resolving

**Comment by kevinthegreat1** [comment]
Sorry but looks like you'll have to rebase this again.

**Comment by kevinthegreat1** [comment]
And I would really appreciate it if you don't reformat the file, cause we have latter prs that would conflict if the file was reformatted.

**Review by kevinthegreat1 — DISMISSED** [review]
> [!Note]
> Squash please

**Review by kevinthegreat1 — APPROVED** [review]

**Pull request merged**
