### PR TITLE
Make TerminalSolver interface & ExperimentSolver class sealed

### PR DESCRIPTION
**Pull request by AzureAaron**
Also made the ExperimentSolver class sealed.

### CODE REVIEW

**Comment by kevinthegreat1** [comment]
I don't get the point of making all the subclasses non-sealed. They shouldn't be extended anyways?

**Comment by AzureAaron** [comment]
> I don't get the point of making all the subclasses non-sealed. They shouldn't be extended anyways?

Make them final instead?

**Comment by kevinthegreat1** [comment]
I didn't realize you have to put either `non-sealed` or `final`. That's really stupid and makes me think that we don't need this at all. But you can choose either `non-sealed` or `final`, I don't really care then.

**Comment by AzureAaron** [comment]
> I didn't realize you have to put either `non-sealed` or `final`. That's really stupid and makes me think that we don't need this at all. But you can choose either `non-sealed` or `final`, I don't really care then.

I swapped them to final as they should not be extended.

**Review by kevinthegreat1 — APPROVED** [review]

**Pull request merged**
