### PR TITLE
Replace tab/playerlist HUD with a more fancy version

### PR DESCRIPTION
**Pull request by msg-programs**
The fancy tab HUD I showed in the discord server in december is finally ready enough for me to open a PR. It replaces the default player list HUD with groups of little widgets that show the same info in a more pretty way.

This is a draft PR for now, as I still feel like some testing needs to be done. Also, as I don't have access to the crimson isle at the moment, this area isn't implemented yet. There are also some more minor issues, as listed in the README for now.

### CODE REVIEW

**Comment by Julienraptor01** [comment]
If you want a tester on crimson isles, you can ask me

**Comment by msg-programs** [comment]
Here we have a first version with the CI HUD that very likely won't work correctly. I'll push the changes later so that they show up in this thread.
[skyblocker-1.8.3-beta-tabmenu+1.19.4.zip](https://github.com/SkyblockerMod/Skyblocker/files/11313575/skyblocker-1.8.3-beta-tabmenu%2B1.19.4.zip) (needs to be renamed from .zip to .jar, thanks GH)
If you find the time, please tell me what kind of errors it threw :)

**Comment by msg-programs** [comment]
[skyblocker-1.9.0-beta-tabmenu+1.19.4.jar.zip](https://github.com/SkyblockerMod/Skyblocker/files/11525347/skyblocker-1.9.0-beta-tabmenu%2B1.19.4.jar.zip)
Thanks to the testing in the discord, this should almost be ready to merge. More testing is still a good idea though.

**Comment by msg-programs** [comment]
[skyblocker-1.9.0+1.19.4.jar.zip](https://github.com/SkyblockerMod/Skyblocker/files/11645614/skyblocker-1.9.0%2B1.19.4.jar.zip)
Another update; this one should hopefully be close to ready for merging.

**Review by AzureAaron — DISMISSED** [review]

**Review by AzureAaron — APPROVED** [review]

**Pull request merged**
