### PR TITLE
Add math teacher helper

### PR DESCRIPTION
**Pull request by Emirlol**
Appends the result and a clickable green text to the math teacher's calculation, calculated using the ``Calculator`` class.

image

### CODE REVIEW

**Comment by viciscat** [comment]
math too hard 😔

**Comment by Fluboxer** [comment]
May as well go extra step and send it for user in chat 
(do same for speaking demon)

**Review by viciscat — APPROVED** [review]
i assume you tested it and that no NPE can occur

**Comment by Emirlol** [comment]
> i assume you tested it and that no NPE can occur

My testing wasn't extensive, but logic-wise it should be covered. And if the calculation fails, it should silently fail and not do anything.

**Review by kevinthegreat1 — DISMISSED** [review]

**Comment by Fluboxer** [comment]
Since we are just in time, can you also make it solve public speaking demon and commitment phobia?

изображение

**Pull request merged**
