### PR TITLE
Make fancy_slot_lock.png

### PR DESCRIPTION
**Pull request by Thsgun**
it may need to be updated depending on how it looks, because it might not contrast with the hotbar well enough compared to the original.

### CODE REVIEW

**Comment by Thsgun** [comment]
alright i got the final version i think

**Comment by Thsgun** [comment]
sorry to screw around again, but do yall want it to be more transparent?

**Comment by Thsgun** [comment]
ok after suggestion, i got rid of the shading for a more shadowy approach, but unfortuneately transparency cannot be applied, which julien is working on rn.

**Comment by Thsgun** [comment]
ok im gonna need to fix it to work with pr 509

**Comment by Thsgun** [comment]
it now has transparency! :)

**Review by kevinthegreat1 — APPROVED** [review]

**Pull request merged**
