### PR TITLE
[Slayers] Adds Slayer Bossbars

### PR DESCRIPTION
**Pull request by BigloBot**
Slayer Bossbars innit

### CODE REVIEW

**Comment by AzureAaron** [comment]
Should cover #908

**Review by kevinthegreat1 — CHANGES_REQUESTED** [review]
I don't think the render mixin is necessary. I would add it to `BossBarHud#bossBars` and remove it when you set the bar to null. The current implementation also stops any other bars from rendering.

**Comment by kevinthegreat1** [comment]
Ok, I'll just make some naming and formatting fixes then.

**Review by kevinthegreat1 — APPROVED** [review]
Works well, thanks!

> [!note]
> Squash please

**Pull request merged**
