### PR TITLE
Add a custom GUI for the Party Finder in dungeons

### PR DESCRIPTION
**Pull request by viciscat**
_Is it pretty? Debatable. Is it useful? Debatable. Did I enjoy making this? ~~Debatable~~ kinda._
Welp here's this thing. This should work but I haven't tested this much since I don't really play Skyblock much anymore. So maybe there's a one in thousand chance edge case scenario.
But there is a decent system where if it doesn't recognize an inventory it reverts back to the vanilla menu.

All widgets added to this aren't meant to be used else where since they are tailored to the whole communicating with the server thing.

Pretty much it I think.

Please do ask questions if you have any.

### CODE REVIEW

**Review by kevinthegreat1 — APPROVED** [review]
Thanks, works great!

**Review by kevinthegreat1 — DISMISSED** [review]
Still works great

**Review by kevinthegreat1 — APPROVED** [review]

**Review by AzureAaron — APPROVED** [review]

**Comment by Thsgun** [comment]
hang on dont merge it

**Comment by Thsgun** [comment]
oh wrong thijng

**Pull request merged**
