### PR TITLE
Dungeons improvements.

### PR DESCRIPTION
**Pull request by Kaluub**
Hello, I have 2 fixes for dungeons, I believe they were reported in Discord as well.
1. Allow dropping protected items if in dungeons.
2. Fix Livid colour text not being replaced.

### CODE REVIEW

**Comment by AzureAaron** [comment]
Not being able to drop protected items in dungeons is **not a bug** and is what’s intended.

**Comment by Kaluub** [comment]
How come it's intended? This prevents you from using your class abilities with (for example) your main weapon. The way I made this fix doesn't allow you to drop protected items from your inventory, only the currently held item, that event is cancelled by Hypixel for your abilities to work

**Comment by Thsgun** [comment]
i think the current mechanic is great, but there should be an option to have it turn off all slot locks when in dungeons

**Comment by AzureAaron** [comment]
> How come it's intended? This prevents you from using your class abilities with (for example) your main weapon. The way I made this fix doesn't allow you to drop protected items from your inventory, only the currently held item, that event is cancelled by Hypixel for your abilities to work

It’s not meant to provide any exceptions for any circumstances. Personally I wouldn’t want to drop my 4B claymore at all anywhere dungeons included.

If you want to add this then it must be behind an option which is disabled by default.

**Comment by Thsgun** [comment]
you cant actuazlly drop items in dungeons, pressing q will instead use your ultimate

**Comment by alexytomi** [comment]
> you cant actuazlly drop items in dungeons, pressing q will instead use your ultimate

You can drop items in dungeons. You just have to do it through the inventory GUI. This doesn't trigger the ultimate.

**Comment by Thsgun** [comment]
the mod cant stop you from dropping from inventory tho

**Comment by alexytomi** [comment]
> the mod cant stop you from dropping from inventory tho

It absolutely does? It sometimes even stops me from putting mt weapon it one of my bags because of it.

**Comment by Kaluub** [comment]
> > How come it's intended? This prevents you from using your class abilities with (for example) your main weapon. The way I made this fix doesn't allow you to drop protected items from your inventory, only the currently held item, that event is cancelled by Hypixel for your abilities to work
> 
> It’s not meant to provide any exceptions for any circumstances. Personally I wouldn’t want to drop my 4B claymore at all anywhere dungeons included.
> 
> If you want to add this then it must be behind an option which is disabled by default.

Okay, I understand. I can add the option in a bit.


> the mod cant stop you from dropping from inventory tho

It does, although it is a different event than the one to drop the currently held item.

**Comment by kevinthegreat1** [comment]
The livid color part looks good.

**Comment by Kaluub** [comment]
> If you want to add this then it must be behind an option which is disabled by default.
Done now.

**Review by kevinthegreat1 — APPROVED** [review]
Code lgtm, didn't test tho.

**Review by AzureAaron — DISMISSED** [review]

**Review by kevinthegreat1 — APPROVED** [review]
You can drop protected items in the entrance, is that desirable?

**Review by kevinthegreat1 — APPROVED** [review]

**Pull request merged**
