### PR TITLE
minor updates

### PR DESCRIPTION
**Pull request by Fix3dll**
conflicts resolved compared to previous closed pr

### CODE REVIEW

**Comment by Fix3dll** [comment]
If we have to say the changes made when I look back:
- more readable and clean PriceInfoTooltip class
- average BIN prices not displayed for pets now its fixed
- when you try to open wiki with shortcut now it not freeze (async)
- when you delete repo or first time using Skyblocker, repository downloading asynchronously. now there is no need to wait for the repository to download for the game to open. especially ideal for slow connections.
- new async `/skyblocker updaterepository` command to update repository. new items, new recipes, new wiki links...
- now we are getting runes avg price from api.
- for wiki link "if wikiLink array index 1 null try to get 0" (this situation is open to improvement and added TODO comment)
sorry if its missing

**Review by kevinthegreat1 — COMMENTED** [review]
The Repository Update command usually is unnecessary right? Since JGit should update the repo on init every time.

**Comment by Fix3dll** [comment]
> The Repository Update command usually is unnecessary right? Since JGit should update the repo on init every time.

Actually the purpose of adding this command was to try async repository update. I didn't delete it after I was done, in case it could be evaluated for debug purposes in the future. I can remove it on request.

**Comment by kevinthegreat1** [comment]
Ah got it. LGTM.

**Review by kevinthegreat1 — APPROVED** [review]

**Pull request merged**
