### PR TITLE
Config Data Fixer

### PR DESCRIPTION
**Pull request by AzureAaron**
Automatically converts the config file to the v2 format if it's in the v1 format. Note that if the migration is successful the old v1 data is overwritten so you cannot go back. If the DFU fails for some reason your configs will be reset however your old config will attempt (and almost certainly because idk how it could fail) be saved in a `skyblocker-1.json` file to allow retrieval of important data.

This also migrates the QuickNav buttons from using Item NBT to now using item components. (And removed the quick nav config class that was duplicated inside itself)

The data fixer will be removed sometime after the foraging update releases (3 weeks) at which point we expect most people to have updated to a skyblocker version with the v2 config format, those who do not update in time will lose their configs.

Important Note: The fixer expects that the config is at least from around 1.14 or newer (but ideally post-YACL), anything older and it may not work; those who haven't updated the mod since this point are on their own if they do not meet this requirement.

### CODE REVIEW

**Review by LifeIsAParadox — DISMISSED** [review]
Only "Starred Mob Bounding Boxes" option was not converted correctly

**Comment by AzureAaron** [comment]
> Only "Starred Mob Bounding Boxes" option was not converted correctly

Fixed now, accidentally misspelt bounding.

**Review by AzureAaron — COMMENTED** [review]
Tried it again with DFU stuff and it works

**Review by LifeIsAParadox — APPROVED** [review]
👍️🍞

**Pull request merged**
