### PR TITLE
Fix some HUD options resetting sometimes

### LINKED ISSUE #336: Dwarven HUD config does not save position
### What happened?

When I change the position of the Dwarven HUD via GUI using the "Dwarven HUD Config..." button and then exit that screen, it does not save the position.

### Screenshots

_No response_

### Log output

https://mclo.gs/oZYWoev

### Minecraft Version

1.20.2

### Skyblocker Version

skyblocker-1.14.0+1.20.2.jar

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AzureAaron**
When you go to a separate UI to configure a HUD position, then go back to the config it no longer forgets what you wanted it to be.

Fixes #336

### CODE REVIEW

**Comment by AzureAaron** [comment]
Removed tip and marked as ready because I don't think there's a better path forward for this.

**Review by kevinthegreat1 — APPROVED** [review]
LGTM. Maybe leave a TODO in `TitleContainerConfigScreen#close`?

**Comment by AzureAaron** [comment]
> LGTM. Maybe leave a TODO in `TitleContainerConfigScreen#close`?

What would the todo be for?

**Comment by kevinthegreat1** [comment]
> > LGTM. Maybe leave a TODO in `TitleContainerConfigScreen#close`?
> 
> What would the todo be for?

It's a slightly janky solution and it might break in the future? Also, we're still waiting for yacl devs to offer some insights for this issue.

**Comment by AzureAaron** [comment]
> > > LGTM. Maybe leave a TODO in `TitleContainerConfigScreen#close`?
> > 
> > 
> > What would the todo be for?
> 
> It's a slightly janky solution and it might break in the future? Also, we're still waiting for yacl devs to offer some insights for this issue.

oh ok, maybe an api idea for YACL is an optional identifier component on options/groups/categories which is defaulted to null that u can set on the option builder.

**Review by kevinthegreat1 — APPROVED** [review]

**Pull request merged**
