### PR TITLE
Aaron's Mod compatibility for profile viewer

### PR DESCRIPTION
**Pull request by AzureAaron**
Adds compatibility for my mod's features in the pv by reformatting text and adding a note to not change the text rendering method used.

### CODE REVIEW

**Comment by x-yingcan-x** [comment]
question: is vanilla slot behavior hard to implement?
most feature broken in current pv, like price info, rarity background(from skyblocker itself), slot highlight when u hover on an item(from vanilla).
anyway, thx for ur time

**Comment by kevinthegreat1** [comment]
Why is this needed? How does your mod work on vanilla items?

**Comment by x-yingcan-x** [comment]
> Why is this needed? How does your mod work on non-skyblocker skyblock items?

whats why i ask for that question, 
> question: is vanilla slot behavior hard to implement?

i think this is caused by skyblocker itself, obviously, the slots in pv are NOT from vanilla (reasons are in the question), so even features from skyblocker itself also need extra compat work as #818 has done.

**Comment by AzureAaron** [comment]
> Why is this needed? How does your mod work on non-skyblocker skyblock items?

It expects the text to be just pure text components, no legacy formatting - Skyblock items on modern versions use text components exclusively. Since the API uses legacy formatting only my item features don’t work out of the box so the text needs to be transformed to be pure components in order for it to work.

**Comment by AzureAaron** [comment]
Now that I think about it maybe its better if I just import the text transformer into Skyblocker, it would be useful to have for the Item DFU as well 🤔

**Comment by kevinthegreat1** [comment]
Also the chroma text part, it would be nicer if you made it so no compat is required on skyblocker’s end, so you do it the same as non-skyblocker skyblock items.

**Comment by AzureAaron** [comment]
> Also the chroma text part, it would be nicer if you made it so no compat is required on skyblocker’s end, so you do it the same as non-skyblocker skyblock items.

Its not reasonable to reimplement the exact same shader, or to handle legacy section symbol formatting when Hypixel doesn't send that.

**Comment by qtlunya** [comment]
I get that code duplication sucks, but forcing people to install another mod to fully utilize a feature of the mod is kinda weird, even if it happens to be made by one of the Skyblocker devs.

If you don't want to duplicate the code into Skyblocker, maybe you could split it out into a library that any mod can depend on.

**Comment by AzureAaron** [comment]
> I get that code duplication sucks, but forcing people to install another mod to fully utilize a feature of the mod is kinda weird, even if it happens to be made by one of the Skyblocker devs.
> 
> If you don't want to duplicate the code into Skyblocker, maybe you could split it out into a library that any mod can depend on.

It's been decided that I will mixin on my side and that we will effectively ban changing the text render method used here lol. And some other small things to ensure compatibility

**Review by kevinthegreat1 — APPROVED** [review]
Lgtm.

**Pull request merged**
