### PR TITLE
Add my dark textures for skyblocker as a default texture pack

### PR DESCRIPTION
**Pull request by Vricken**
A lot of people use dark mode so I thought it would be nice to have it directly in the mod for ease of use

(Merging this would mean being able to remove the texture pack from the mod pack)

### CODE REVIEW

**Comment by kevinthegreat1** [comment]
Use `Identifier.of()` instead of `new Identifier()`. You can thank mojang for that one.

**Comment by LifeIsAParadox** [comment]
Maybe it would be best if you make a pr at Default-Dark-Mode

**Comment by viciscat** [comment]
I think having a new class JUST to register the resourcepack is excessive

**Comment by Vricken** [comment]
> Maybe it would be best if you make a pr at Default-Dark-Mode

Sure I can do that

**Comment by Vricken** [comment]
I made a pr at the Default-Dark-Mode github it was the most obvious course of action no idea why I didn't think of it right away

**Pull request closed without merging**
