### PR TITLE
Fully configureable Fancy Tab HUD

### PR DESCRIPTION
**Pull request by msg-programs**
The long-awaited customizeable fancy tab is finally (almost) here! 
You can now specify your own layouts using some JSON files and load them via a resource pack. There's also a builtin resource pack for a top-aligned layout and a README containing some docs about how to write layout files.

Needs testing. The top aligned layout needs some work and the `collide` op doesn't work for all of the values that might be useful, which is TODO at the moment. Hence, this is just a draft for the moment

### CODE REVIEW

**Comment by kevinthegreat1** [comment]
Looks great so jar! Maybe add a format version to the resource pack format in case we need to make breaking changes? I don't know if you can put extra stuff in `pack.mcmeta` or somewhere. I'm also a bit worried about clearing the components and rebuilding every frame.

**Comment by msg-programs** [comment]
There we go, should be good to merge after some double checking

**Review by AzureAaron — CHANGES_REQUESTED** [review]

**Comment by kevinthegreat1** [comment]
Push some refactors which Intellij was yelling at me for. Tested this by going to random skyblock island and seems to work. Also, is the intended name of the resource pack to be "skyblocker/default_top"? Don't think that's a very user friendly name lol.

**Comment by AzureAaron** [comment]
> Pushed some refactors which Intellij was yelling at me for. Tested this by going to random skyblock island and seems to work.
> 
> Also, is the intended name of the resource pack to be "skyblocker/default_top"? Don't think that's a very user friendly name lol.

I would just add to the pack's description instead of changing the packs name

**Review by AzureAaron — APPROVED** [review]

**Review by LifeIsAParadox — APPROVED** [review]
lgtm

**Pull request merged**
